-- SQLite
-- Excluindo uma t abela no bd

-- Table Users
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME_USER TEXT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(8) NOT NULL
);

-- Excluindo a tabela users
DROP TABLE USERS;