SELECT C.NAME AS 'NOME DO CLIENTE',
  CA.NAME AS 'CARRO',
  E.NAME AS 'FUNCIONÁRIO',
  L.*
 FROM LOCATIONS AS L

  INNER JOIN CUSTOMERS AS C ON (C.ID = L.CUSTOMER_ID)
  INNER JOIN CARS AS CA ON (CA.ID = L.CAR_ID)
  INNER JOIN EMPLOYEES AS E ON (E.ID = L.EMPLOYEE_ID);