CREATE TABLE CUSTOMERS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR(128) NOT NULL,
  LASTNAME VARCHAR2(155) NOT NULL,
  PHONE VARCHAR2(16) NOT NULL,
  EMAIL VARCHAR2(32) NOT NULL,
  ADDRESS VARCHAR(200) NOT NULL,
  CITY VARCHAR(64) NOT NULL,
  STATE VARCHAR(2) NOT NULL,
  BIRTH_DATE DATETIME NOT NULL
);